DEV-525 Add EwbDataFilePaths to python sdk
zepben/ewb-sdk-python pull request #149
Opened 2024-05-10 04:53 UTC by vincewhite

# Description

Mirror the functionality of EwbDataFilePaths it the jvm sdk. 

# Associated tasks

JVM version: https://github.com/zepben/evolve-sdk-jvm/pull/163

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
- [ ] I have performed a self review of my own code (including checking issues raised when creating the PR).
- [x] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.
- [x] I have commented my code in any hard-to-understand or hacky areas.
- [x] I have handled all new warnings generated by the compiler or IDE.
- [x] I have rebased onto the target branch (usually main).
      
### Documentation
- [x] I have updated the changelog.
- [x] I have updated any documentation required for these changes.

# Breaking Changes
- [x] I have considered if this is a breaking change and will communicate it with other team members if so.

Helper class, all new functionality, not currently used by any of our code.

2024-05-10 04:53 UTC, ryanjcoleman commented
Task linked: [DEV-525 Update Python SDK](https://app.clickup.com/t/6929263/DEV-525)

2024-05-14 08:07 UTC, kgreav requested changes

2024-05-14 08:07 UTC, kgreav commented on src/zepben/evolve/database/paths/ewb_data_file_paths.py
> +    list_files: Callable[[Path], Iterator[Path]] = None
This is not a dataclass, so probably remove all these as they are class variables rather than instance variables.

2024-05-14 08:07 UTC, kgreav commented on src/zepben/evolve/database/paths/ewb_data_file_paths.py
> +                 create_directories_func: Callable[[Path], Path] = lambda it: it.mkdir(parents=True),  # TODO: actually return Path or change sig?
seems like you settled on returning to the path - good job stay on the path and remove this TODO.

2024-06-05 06:55 UTC, kgreav approved these changes

2024-06-05 06:55 UTC, merged